### ISSUE TITLE
Support for triggering Lambda Functions via Scheduled Events

### ISSUE THREAD

**Issue by alye** [awslabs/chalice#102]
I think this would be a very handy feature to incorporate. WDYT?

**Comment by jamesls** [comment]
This was previously discussed here: https://github.com/awslabs/chalice/issues/49

The summary of that issue is that while I think this would be really useful, my primary focus right now is going to be improving the experience for writing rest APIs with API Gateway and AWS Lambda.  I'm considering adding events support but I'd need to think about a) if that belongs in `chalice` or some other chalice extension package b) how you'd structure your app to support events (and multiple lambda functions in general).

So I'm going to mark it as out of scope for now, but I am interested to hear other people's thoughts and ideas on what this would look like.

If there's enough interest I might create a tracking issue where we can collect all the proposals ideas to a single thread.
