### ISSUE TITLE
Alternate content types not added in API Gateway

### ISSUE THREAD

**Issue by stannie** [awslabs/chalice#119]
Tried this while playing around with non-JSON payloads:
```
@app.route('/introspect', methods=['GET','HEAD','POST','PUT','DELETE'],
                          content_types=['application/json', 'application/jwt'])
def introspect():
    return app.current_request.to_dict()
```

But then this results in a **415 Unsupported Media Type** : 
```
curl -X POST -d "eyXXX.XXX" -H "Content-Type: application/jwt" https://endpoint/dev/introspect
```
and indeed `application/jwt` is not in the Body Mapping Templates on the API Gateway.

**Comment by chrismcmacken** [comment]
👍  Alternate content-types do not work. They always produce 415 unsupported media type, even after adding them to the route as the readme indicates.

**Comment by jamesls** [comment]
I think this was due to the fact that there was a delay between when the README was updated (which tracks the develop branch) and when this made it into an official release on pypi.  I've verified that this works now as expected:

```
$ http https://endpoint/dev/introspect 'Content-Type: application/jwt' | jp headers
{
  "accept": "*/*",
  "accept-encoding": "gzip, deflate",
  "cloudfront-forwarded-proto": "https",
  "cloudfront-is-desktop-viewer": "true",
  "cloudfront-is-mobile-viewer": "false",
  "cloudfront-is-smarttv-viewer": "false",
  "cloudfront-is-tablet-viewer": "false",
  "cloudfront-viewer-country": "US",
  "content-type": "application/jwt",
  "user-agent": "HTTPie/0.9.3",
  "x-forwarded-port": "443",
  "x-forwarded-proto": "https"
}
```

I'm going to make some changes so a decent error messages is produced when using an unsupported feature.  Right now the route methods take `**kwargs` and ignores unknown kwargs.  Let me know if you're still running into issues on the latest version of chalice.
