### ISSUE TITLE
Deploy fails: "The security token included in the request is invalid"

### ISSUE THREAD

**Issue by MohAlRej** [awslabs/chalice#152]
I've just installed Chalice and followed the demo, every time I hit Chalice deploy I get:

`
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the GetFunction operation: The security token included in the request is invalid.
`

I'm not sure what's the reason

**Comment by jamesls** [comment]
That usually happens when you either don't have access to lambda or your credentials (in this case it looks like temporary credentials) are invalid.

Here's a few things you can try:

1. Making an API call to another service, for example try: `aws apigateway get-rest-apis`
2. Making an API call to `get-function`: `aws lambda get-function --function-name $(aws lambda list-functions --query Functions[0].FunctionName --output text)`

Do those commands work for you?
