### ISSUE TITLE
unable to import module 'app', no named module 'requests'

### ISSUE THREAD

**Issue by SooLee** [awslabs/chalice#189]
My app.py contains `import requests` and I included `requests==2.11.1` in `requirements.txt` along with other modules. It is the same version that I installed using pip install requests. 

```
pip freeze |grep requests
requests==2.11.1
```

My requirements file:
```
json
urllib
boto3==1.4.1
requests==2.11.1 
time
sys
random
```

The first 10 lines of `app.py`
```
from __future__ import print_function
from chalice import Chalice

import json
import urllib
import boto3 ## 1.4.1 (not the default boto3 on lambda)
import requests 
import time
import sys
import random
```

The first few lines of the lambda handler function (main)
```
@app.route("/",methods=["POST"])
#def lambda_handler(event, context):
def lambda_handler():
    event = app.current_request.json_body
```

When I do `chalice local`, the app works fine with httpie, but with `chalice deploy` I get that 'unable to import module 'app' error. CloudWatch log says 'no named module 'requests'. 

Any idea?

**Comment by SooLee** [comment]
By the way the app also works well when directly deployed on lambda without APIGateway / Chalice (except that I didn't get APIGateway to work with it). I just changed the code as follows, so I can use with Chalice:

From
```
def lambda_handler(event, context):
```
to

```
@app.route("/",methods=["POST"])
def lambda_handler():
    event = app.current_request.json_body
```

So that it takes input from app.current_request rather than the event argument of the lambda_handler function.

**Comment by SooLee** [comment]
I got it resolved by starting fresh. I had started with an existing (working) lambda function that I had created without chalice. There were already boto3 and requests installed inside the directory fr that function to work (deleting them didn't help.) For some reason, that didn't work.

**Comment by ngmcfarland** [comment]
I have been having the same issue, but I think I found what was causing it for me. I have been using Chalice from an AWS Linux EC2 instance and could not get anything from my requirements.txt to be included with the deployment. After a lot of digging, I discovered that it was due to Chalice looking for installed dependencies in the "site-packages" directory of my virtualenv environment, but pip was installing them in the "dist-packages" directory. I made a local change to Chalice in the compat.py file as a workaround, but I'm not sure what the more long term solution should be.
