### ISSUE TITLE
Local Response Headers

### ISSUE THREAD

**Issue by nplutt** [awslabs/chalice#217]
Hi, it would be really nice if there were a way to configure what headers are returned from the local server.  Our current idea is to add an array of accepted headers to the config.json file.

Thanks,
Nick

**Comment by jamesls** [comment]
Would these be headers you want added to every response or would you want different headers per each view function?

Out of curiosity, how would plan on using this?  To match the exact headers returned by API Gateway?  Because if that's the case it might make sense to just make that built in to the local dev server.

**Comment by nplutt** [comment]
Currently there is no way to configure the response headers that API gateway returns. For example there is currently no way to return a location header with a 201 response.

**Comment by jamesls** [comment]
Closing out old issue, this should now be possible to control the status code and headers using the `Response` object.  See [the tutorial](http://chalice.readthedocs.io/en/latest/quickstart.html#tutorial-customizing-the-http-response) for an example of this.
