### ISSUE TITLE
Need a way of running the Lambda service locally

### ISSUE THREAD

**Issue by marvinpinto** [awslabs/chalice#22]
This would be great for testing and iterating locally, vs deploying and then validating.

(I couldn't find any references to this in the docs or source code, so apologies if this is already a feature)

**Comment by jamesls** [comment]
I agree, thanks for the feature request.  This is something I plan on adding.

**Comment by jvkumar** [comment]
👍

**Comment by moselaymd** [comment]
👍

**Comment by dannymcpherson** [comment]
👍🏻

**Comment by vigilantzealot** [comment]
yes! please do, i boiler-plated it under flask, but it flask uses <> brackets for url params and accesses url params differently - bleh waster 2 hours.

something please! soon please!

**Comment by green-latte** [comment]
Yes! And I wanna create custom class to execute just like `python app.py runserver` or `python app.py test --with-report`

**Comment by sscarduzio** [comment]
this is super urgent for IRL usage of this framework, deploying takes forever and error messages in remote logs are super generic (no exception propagation)

**Comment by jamesls** [comment]
https://github.com/awslabs/chalice/pull/147 has been merged, which adds support for `chalice local`.  I'll have a release out soon, try it out and let me know if you have any feedback.

Btw, the rationale for not propagating exceptions by default is so that you don't leak internal information in your error responses.  You can set `app.debug = True` in your `app.py` file, and the exceptions will propagate back to you.

That being said, hopefully `chalice local` makes this unnecessary :)
