### ISSUE TITLE
Chalice doesn't create resources beyond index

### ISSUE THREAD

**Issue by colde** [awslabs/chalice#26]
When using the sample from the docs e.g.:

```python
from chalice import Chalice

app = Chalice(app_name='helloworld')

CITIES_TO_STATE = {
    'seattle': 'WA',
    'portland': 'OR',
}

@app.route('/')
def index():
    return {'hello': 'world'}

@app.route('/cities/{city}')
def state_of_city(name):
    return {'state': CITIES_TO_STATE[name]}
```

Chalice doesn't seem to create any resources beyond the index route. And attempting to call dev/cities/seattle returns a missing authentication error.

**Comment by jamesls** [comment]
It sounds like the app didn't actually deploy.  I'm not able to reproduce.  These are the resources I see when I copy/paste/deploy the above code:

![image](https://cloud.githubusercontent.com/assets/368057/16775813/43189086-4817-11e6-8e22-60daf335c27d.png)

I'd double check the `chalice deploy` command didn't fail.  Otherwise, any additional information you can share would be helpful.

**Comment by colde** [comment]
@jamesls Yeah, i am guessing it didn't deploy correctly either. However, if creating an entirely new project, and deploying it. It does create the root endpoint for me, but not the sub ones.

Here is the output of the command while deploying:
`Updating IAM policy.
Updating lambda function...
Regen deployment package...
Sending changes to lambda.
Lambda deploy done.
API Gateway rest API already found.
Deleting root resource id
Done deleting existing resources.
Deploying to: dev
https://<endpoint>/dev/`

Is there a way to get a logfile somewhere with more detailed info?

**Comment by colde** [comment]
Seems it was user error. For some reason, my editor wasn't saving correctly.
