### ISSUE TITLE
Error using boto3 client with lambda & chalice 0.7.0

### ISSUE THREAD

**Issue by NanoMarc** [awslabs/chalice#288]
=== Version ===

boto3 : 1.4.4
chalice : 0.7.0

=== Steps to reproduce ===

- I created a view to request a queue

> @app.route('/list/stack', methods=['PUT'])
def listStack(): #Key is the table name here
    try:
        print("=== Function list/stack : Initiated ===")
        # Get request
        request = app.current_request

        ## send incoming request to a queue
        # Create SQS client
        print("== Create SQS client : Initiated ==")
        client_sqs = boto3.client('sqs')
        print("== Create SQS client : Done ==")

        # List SQS queues
        print("== List Queues : Initiated ==")
        queues = client_sqs.list_queues()
        print("== List Queues : Done ==")
        return queues
    except ClientError as e:
        raise NotFoundError()

> 

- It is working fine.
- Then I decided to use exactly the same view to list a bucket.

> 

@app.route('/list/stack', methods=['PUT'])
def listStack(): #Key is the table name here
    try:
        print("=== Function list/stack : Initiated ===")
        # Get request
        request = app.current_request

        ## send incoming request to a queue
        # Create SQS client
        print("== Create SQS client : Initiated ==")
        client_sqs = boto3.client('s3')
        print("== Create SQS client : Done ==")

        # List SQS queues
        print("== List Queues : Initiated ==")
        queues = client_sqs.list_buckets()
        print("== List Queues : Done ==")
        return queues
    except ClientError as e:
        raise NotFoundError()

> 

- I replaced sqs by s3 and list_queues() by list_buckets()

=== Expected Result ===

- I have my buckets' list

=== Actual Result ===

- I have an error 502 Bad Gateway : Internal Server Error
- When I check the logs from the lambda function, I have the following issue : 
- Circular reference detected: ValueError Traceback (most recent call last): File "/var/task/chalice/app.py", line 312, in __call__ return response.to_dict() File "/var/task/chalice/app.py", line 145, in to_dict body = json.dumps(body, default=handle_decimals) File "/usr/lib64/python2.7/json/__init__.py", line 251, in dumps sort_keys=sort_keys, **kw).encode(obj) File "/usr/lib64/

> 

Circular reference detected: ValueError
Traceback (most recent call last):
File "/var/task/chalice/app.py", line 312, in __call__
return response.to_dict()
File "/var/task/chalice/app.py", line 145, in to_dict
body = json.dumps(body, default=handle_decimals)
File "/usr/lib64/python2.7/json/__init__.py", line 251, in dumps
sort_keys=sort_keys, **kw).encode(obj)
File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
return _iterencode(o, 0)
ValueError: Circular reference detected

> 

- I don't really know what this issue mean.

**Comment by stealthycoin** [comment]
Thats because the response from list_buckets contains `datetime.datetime` objects which the default `json.dumps` function does not know how to handle. Currently Chalice only adds decimals to the default set of json serializable types: https://github.com/awslabs/chalice/blob/master/chalice/app.py#L256 which means you need to process the list and change the datetime.datetime into some other type. Chalice cannot do this for you by default because there are too many options, which can be useful in different situations, its up to you to pick one. 

Although it may be useful to be able to override the default json encoder class now that the `Response` object is exposed.

**Comment by aanilpala** [comment]
I also had the Circular reference error when trying to make a gateway-api for my sagemaker model. My model returns json and there is no datetime in the response. I realized the problem is that your `handle_request` method does not handle StreamingBody Response. I fixed the issue by simply adding `body['Body'] = body['Body'].read().decode("utf-8")` in `to_dict` method of `Respnse` class located in chalice/app.py

I was using Chalice version 1.7.0
