### ISSUE TITLE
Custom Package in vendor folder not recognized

### ISSUE THREAD

**Issue by abcondas** [awslabs/chalice#349]
I have a custom package called datareferencecommon that exists in our company's private artifactory.  As instructed in chalice/docs/source/topics/packaging.rst I added a vendor folder at the same level as my app.py file.  I created a datareferencecommon folder and loaded all of the *.py files into this folder.  Folder looks like this:
```
root
    |--- chalicelib
    |--- app.py
    |--- requirements.txt
    |--- vendor
          |--- datareferencecommon
                 |--- __init__.py
                 |--- config.py
                 |--- discovery.py
                 |--- utils.py
```

In app.py, there is a statement: `from datareferencecommon import discovery, utils`
I ran chalice deploy from the root folder and receive an error "no module named datareferencecommon".  What am I doing wrong?  Thanks.

Also, am I understanding this correctly?  chalice deploy won't install from a private artifactory even if the ~/.pypirc file exists and points appropriately to the private artifactory?

**Comment by stealthycoin** [comment]
This looks like a bug to me. We load the `app.py` locally during deployment for validation and finding some configuration values, but this happens before packaging where the vendored folder contents are hoisted up to the top level with `app.py`, so the imports fail locally even though they would succeed in the lambda function.

As a temporary workaround you can import the vendored things things you need inside the routes where you actually need the functions, since the deployment process does not call any of the routes this won't cause an import error, and the imports work properly once deployed to the lambda function.

```python
from chalice import Chalice

app = Chalice(app_name='test-vendor')


@app.route('/')
def index():
    from datareferencecommon.utils import fetch_something
    return {'hello': fetch_something()}
```
