### ISSUE TITLE
csrf attack prevention?

### ISSUE THREAD

**Issue by watdeo** [awslabs/chalice#383]
With Chalice, is there a way to generate and verify a csrf token across lambda functions, so that I can verify the token once the user submits a form? Flask uses the CSRFProtect module to protect its app from csrf attacks. Does Chalice have something similar?

If not, what's would be best practice when dealing with this problem?

**Comment by dstufft** [comment]
There is currently not any abstractions built into Chalice to let you manage a CSRF token, I think that this would be a good feature request for Chalice to add though, since it is something that is commonly needed in a web application and it can be a little bit fiddly to get right.

If you want to implement this yourself and you're using a form library, you might look at that form library since many of them in Python do come with CSRF support either directly or via an extension. If it does not, then my recommendation would be to use what OWASP calls a Synchronizer Token which is the strategy used by Django by default (and I *believe* Flask uses it too).

You can read more about that [On the OWASP website](https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Synchronizer_.28CSRF.29_Tokens), but it basically boils down to saving a securely generated random value to a cookie, and storing that same value in the HTML as a hidden form field, then on a POST or other non-safe HTTP method check the value of that hidden form against the value in the cookie (using a constant time compare, like ``hmac.compare_digest()``). There are other styles available and the main ones are also on that page on OWASP, but they all generally require storing some state on the server side.
