### ISSUE TITLE
chalice deploy fails when environment variable is not set

### ISSUE THREAD

**Issue by cliffano** [awslabs/chalice#441]
My app uses an environment variable:

```
import os
blah = os.environ['foobar']
```

When I try to deploy it, it fails after simply showing the expected environment variable name:

```
boruto> chalice deploy
'foobar'
```

I have set the environment variable in config.json . However the deployment shouldn't expect such variable to exist because it's possible that the value can be created/modified post-deployment by a separate action.

The workaround I'm using for now is to set an empty environment variable during deployment:

```
boruto> foobar= chalice deploy
Updating IAM policy.
Updating lambda function...
Regen deployment package...
Updating IAM policy.
Sending changes to lambda.
API Gateway rest API already found.
Deploying to: dev
https://abcdef.execute-api.us-west-2.amazonaws.com/dev/
```

Tested with chalice 1.0.0b1:

```
boruto> chalice --version
chalice 1.0.0b1
```

**Comment by stealthycoin** [comment]
I would need to see your code to see what exactly is happening. Chalice loads the app.py file in order to do some basic validation and run the analyzer over your code to generate a policy file for your Lambda function. If you have any code sitting at the module level in your app.py file then it will get executed, so any errors it throws will derail the deployment.

If you have any module level code it should probably be moved or written in such a way as to not throw an error. You could change it to `blah = os.environ.get('foobar')` instead so its a `None` instead of raising an error.

**Comment by cliffano** [comment]
@stealthycoin As you suggested, changing it to `os.environ.get` to avoid an error works out for me.
I missed out the need to handle error at the module level.

Thanks for the pointer. Much appreciated.
